[book]
title = "Example book"
authors = ["kimbeomgyu"]
description = "The example book covers examples."
language = "ko-KR"
text-direction = "ltr"

[rust]
edition = "2021"

[build]
build-dir = "docs"

[output.html]
default-theme = "rust"
